name: open_file_manager
description: A flutter plugin to open default file manager app. on an Android, it opens Download folder on selected file manager app. on iOS, it opens app folder in default Files app.
version: 0.0.2
homepage: https://github.com/nayanAubie/open_file_manager
repository: https://github.com/nayanAubie/open_file_manager

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aubergine.open_file_manager
        pluginClass: OpenFileManagerPlugin
      ios:
        pluginClass: OpenFileManagerPlugin
